version: "3.7"
services:
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./config:/mosquitto/config:rw
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw
    networks:
      - nginx-net
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: arthur/teste
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      JWT_SECRET: "teste"
      MQTT_HOST: "tcp://mqtt5:1883"
      MQTT_USER: "user1"
      MQTT_PASS: "hotel2202"
    depends_on:
      - mqtt5
    networks:
      - nginx-net
    ports:
      - "4000:4000"
    expose:
      - "4000"
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      # - ./nginx/certs:/etc/nginx/certs
    networks:
      - nginx-net
    depends_on:
      - app
# volumes for mapping data,config and log
volumes:
  config:
  data:
  log:

networks:
  nginx-net:
  default:
    name: mqtt5-network
